### ISSUE TITLE
Update of libs?

### ISSUE THREAD

**Issue by Neustradamus** [igniterealtime/Openfire-connectionmanager#2]
I have discovered that there are a lot of very old libs:
- https://github.com/igniterealtime/Openfire-connectionmanager/blob/master/build/lib/versions.txt
- https://github.com/igniterealtime/Openfire-connectionmanager/tree/master/build/lib

Can you update it for security?

There are a lot of CVEs.

**Comment by Neustradamus** [comment]
@guusdk: One example, CVEs here:
- https://github.com/igniterealtime/Openfire-connectionmanager/blob/master/build/lib/versions.txt#L6

**Comment by guusdk** [comment]
This project has not seen any activity for 6 years. It is no longer maintained. I'm not going to apply changes with might cause people to think that it is.

Instead, I will archive this project.
